openapi: 3.0.3
info:
  title: Star Wars API DigiChanges
  description: API Star Wars for DigiChanges challenge
  version: 1.0.0

paths:
  /films:
    # Ruta para obtener todas las películas
    get:
      tags:
        - films
      summary: Get all films
      description: Retrieves information for all films.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                  - title: A New Hope
                    episode_id: 4
                    opening_crawl: It is a period of civil war.
                    director: George Lucas
                    producer: Gary Kurtz, Rick McCallum
                    release_date: "1977-05-25"
                    characters:
                      - 1
                      - 2
                    planets:
                      - https://swapi.dev/api/planets/1/
                      - https://swapi.dev/api/planets/2/
                    created: "2014-12-10T14:23:31.880000Z"
                    edited: "2014-12-20T19:49:45.256000Z"
                    url: https://swapi.dev/api/films/1
        '500':
          description: Internal server error

  /films/{id}:
    # Ruta para obtener una película por su ID
    get:
        tags:
        - films
        summary: Get film by ID
        description: Retrieves information for a film based on its ID.
        parameters:
        - name: id
          in: path
          required: true
          description: ID of the film to retrieve
          schema:
            type: string
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                example: 
                  - title: A New Hope
                    episode_id: 4
                    opening_crawl: It is a period of civil war.
                    director: George Lucas
                    producer: Gary Kurtz, Rick McCallum
                    release_date: "1977-05-25"
                    characters:
                      - 1
                      - 2
                    planets:
                      - https://swapi.dev/api/planets/1/
                      - https://swapi.dev/api/planets/2/
                    created: "2014-12-10T14:23:31.880000Z"
                    edited: "2014-12-20T19:49:45.256000Z"
                    url: https://swapi.dev/api/films/1
          '404':
              description: Film not found
          '500':
              description: Internal server error

  /planets:
    # Ruta para obtener todas los planetas
    get:
      tags:
        - planets
      summary: Get all planets
      description: Retrieves information for all planets.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                  - name: Tatooine
                    rotation_period: 23
                    orbital_period: 304
                    diameter: 10465
                    climate: arid
                    gravity: 1 standard
                    terrain: desert
                    surface_water: 1
                    population: 200000
                    residents:
                      - 1
                      - 2
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/3/
                    created: "2014-12-09T13:50:49.641000Z"
                    edited: "2014-12-20T20:58:18.411000Z"
                    url: https://swapi.dev/api/planets/1
        '500':
          description: Internal server error
        
  /planets/{id}:
    # Ruta para obtener un planeta por su ID
    get:
        tags:
        - planets
        summary: Get planet by ID
        description: Retrieves information for a planet based on its ID.
        parameters:
        - name: id
          in: path
          required: true
          description: ID of the planet to retrieve
          schema:
            type: string
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
               example: 
                  - name: Tatooine
                    rotation_period: 23
                    orbital_period: 304
                    diameter: 10465
                    climate: arid
                    gravity: 1 standard
                    terrain: desert
                    surface_water: 1
                    population: 200000
                    residents:
                      - 1
                      - 2
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/3/
                    created: "2014-12-09T13:50:49.641000Z"
                    edited: "2014-12-20T20:58:18.411000Z"
                    url: https://swapi.dev/api/planets/1
          '404':
            description: Planet not found
          '500':
            description: Internal server error

  /people:
    # Ruta para obtener todas las personas
    get:
      tags:
        - people
      summary: Get all people
      description: Retrieves information for all people.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                  - name: Luke Skywalker
                    height: 172
                    mass: 77
                    hair_color: blond
                    skin_color: fair
                    eye_color: blue
                    birth_year: 19BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    created: "2014-12-09T13:50:51.644000Z"
                    edited: "2014-12-20T21:17:56.891000Z"
                    url: https://swapi.dev/api/people/1
        '500':
          description: Internal server error

  /people/{id}:
    # Ruta para obtener una persona por su ID
    get:
      tags:
        - people
      summary: Get person by ID
      description: Retrieves information for a person based on their ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the person to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                  - name: Luke Skywalker
                    height: 172
                    mass: 77
                    hair_color: blond
                    skin_color: fair
                    eye_color: blue
                    birth_year: 19BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    created: "2014-12-09T13:50:51.644000Z"
                    edited: "2014-12-20T21:17:56.891000Z"
                    url: https://swapi.dev/api/people/1
        '404':
          description: Person not found
        '500':
          description: Internal server error
  
  /starships:
    # Ruta para obtener todas las starships
    get:
      tags:
        - starships
      summary: Get all starships
      description: Retrieves information for all starships.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                  - name: CR90 corvette
                    model: CR90 corvette
                    manufacturer: Corellian Engineering Corporation
                    cost_in_credits: 3500000
                    length: 150
                    max_atmosphering_speed: 950
                    crew: 30-165
                    passengers: 600
                    cargo_capacity: 3000000
                    consumables: 1 year
                    hyperdrive_rating: 2.0
                    MGLT: 60
                    starship_class: corvette
                    pilots: []
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    created: "2014-12-10T14:20:33.369000Z"
                    edited: "2014-12-20T21:23:49.867000Z"
                    url: https://swapi.dev/api/starships/2/
        '500':
          description: Internal server error
        
  /starships/{id}:
    # Ruta para obtener una starship por su ID
    get:
      tags:
        - starships
      summary: Get starship by ID
      description: Retrieves information for a starship based on its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the starship to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example: 
                  - name: CR90 corvette
                    model: CR90 corvette
                    manufacturer: Corellian Engineering Corporation
                    cost_in_credits: 3500000
                    length: 150
                    max_atmosphering_speed: 950
                    crew: 30-165
                    passengers: 600
                    cargo_capacity: 3000000
                    consumables: 1 year
                    hyperdrive_rating: 2.0
                    MGLT: 60
                    starship_class: corvette
                    pilots: []
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    created: "2014-12-10T14:20:33.369000Z"
                    edited: "2014-12-20T21:23:49.867000Z"
                    url: https://swapi.dev/api/starships/2/
        '404':
          description: Starship not found
        '500':
          description: Internal server error

components:
  schemas:
    Film:
      type: object
      properties:
        title:
          type: string
        episode_id:
          type: integer
        opening_crawl:
          type: string
        director:
          type: string
        producer:
          type: string
        release_date:
          type: string
          format: date
        characters:
          type: array
          items:
            type: string
        planets:
          type: array
          items:
            type: string
        created:
          type: string
          format: date-time
        edited:
          type: string
          format: date-time
        url:
          type: string

    Planet:
      type: object
      properties:
        name:
          type: string
        rotation_period:
          type: string
        orbital_period:
          type: string
        diameter:
          type: string
        climate:
          type: string
        gravity:
          type: string
        terrain:
          type: string
        surface_water:
          type: string
        population:
          type: string
        residents:
          type: array
          items:
            type: string
        films:
          type: array
          items:
            type: string
        created:
          type: string
        edited:
          type: string
        url:
          type: string

    Person:
      type: object
      properties:
        name:
          type: string
        height:
          type: string
        mass:
          type: string
        hair_color:
          type: string
        skin_color:
          type: string
        eye_color:
          type: string
        birth_year:
          type: string
        gender:
          type: string
        homeworld:
          type: string
        films:
          type: array
          items:
            type: string
        created:
          type: string
        edited:
          type: string
        url:
          type: string

    Starship:
      type: object
      properties:
        name:
          type: string
        model:
          type: string
        manufacturer:
          type: string
        cost_in_credits:
          type: string
        length:
          type: string
        max_atmosphering_speed:
          type: string
        crew:
          type: string
        passengers:
          type: string
        cargo_capacity:
          type: string
        consumables:
          type: string
        hyperdrive_rating:
          type: string
        MGLT:
          type: string
        starship_class:
          type: string
        pilots:
          type: array
          items:
            type: string
        films:
          type: array
          items:
            type: string
        created:
          type: string
          format: date-time
        edited:
          type: string
          format: date-time
        url:
          type: string
